---
minimal_mistakes_skin: default
locale: en-US
rtl: null
title: Lachlan Haydon
title_separator: "-"
subtitle: null
name: Lachlan Haydon
description: A Portfolio and Blog of Some of My Projects
url: https://lachlan.site
baseurl: null
repository: lachlanhaydon/lachlanhaydon.github.io
teaser: null
logo: null
masthead_title: null
breadcrumbs: null
words_per_minute: 200
enable_copy_code_button: null
copyright: null
copyright_url: null
comments:
  provider: null
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
  utterances:
    theme: null
    issue_term: null
  giscus:
    repo_id: null
    category_name: null
    category_id: null
    discussion_term: null
    reactions_enabled: null
    theme: null
    strict: null
    input_position: null
    emit_metadata: null
    lang: null
    lazy: null
  staticman:
    branch: null
    endpoint: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
  hide: null
search: null
search_full_content: null
search_provider: null
lunr:
  search_within_pages: null
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
naver_site_verification: null
yandex_site_verification: null
baidu_site_verification: null
twitter:
  username: null
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: null
  google:
    tracking_id: null
    anonymize_ip: null
author:
  name: Lachlan Haydon
  avatar: /assets/images/profile.jpg
  bio: Senior at Loyola Chicago | Student Researcher for the Telescope Array Project
  location: Chicago, IL | Bay Area, CA
  email: null
  links:
    - label: lachhaydon@gmail.com
      icon: fas fa-fw fa-envelope-square
    - label: GitHub
      icon: fab fa-fw fa-github
    - label: LinkedIn
      icon: https://www.linkedin.com/in/lachlanhaydon/
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/lachlanhaydon
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://linkedin.com/in/yourprofile
  since: "2026"
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
timezone: null
paginate: 5
paginate_path: /page:num/
pagination:
  debug: false
  collection: posts
  per_page: 10
  permalink: /page/:num/
  title: :title - page :num
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: null
      share: true
      related: true
